DROP DATABASE IF EXISTS "scalabackendsampling";

DROP ROLE IF EXISTS scalabackendsampling;

CREATE ROLE scalabackendsampling LOGIN
ENCRYPTED PASSWORD '79fc63089470aa2d160ed21864a0127d'
SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;

CREATE DATABASE "scalabackendsampling"
WITH OWNER = scalabackendsampling
ENCODING = 'UTF8'
TABLESPACE = pg_default
CONNECTION LIMIT = -1;